# Generated by Django 2.2.7 on 2019-12-03 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('workId', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('years', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='work', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work',
                'db_table': 'Work',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('volunteerId', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.TextField(null=True)),
                ('jobs', models.TextField(null=True)),
                ('years', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Volunteer',
                'db_table': 'Volunteer',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skillId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('level', models.TextField(null=True)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='skill', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'db_table': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('occupation', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('bio', models.TextField(null=True)),
                ('contactmessage', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('userId', models.OneToOneField(db_column='actionId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('educationId', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.TextField(null=True)),
                ('degree', models.TextField(null=True)),
                ('graduated', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('userId', models.OneToOneField(db_column='actionId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education',
                'db_table': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('province', models.TextField(null=True)),
                ('zip', models.TextField(null=True)),
                ('userId', models.OneToOneField(db_column='actionId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'db_table': 'Address',
            },
        ),
    ]
