# Generated by Django 3.0 on 2020-04-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('verificationId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(editable=False)),
                ('code', models.CharField(editable=False, max_length=6, unique=True)),
            ],
            options={
                'verbose_name': 'Verification',
                'db_table': 'Verification',
            },
        ),
    ]
